##
## Build with Travis.CI
##
sudo: required

language: generic

services:
  - docker

script:
- |
  baseDir="$(pwd)"
  echo "Base directors is '$baseDir'."
  inputDir="${baseDir}/book"
  outputDir="${baseDir}/output"
  echo "Input directory is '$inputDir' and output directory is '$outputDir'."
  mkdir -p "${outputDir}"
  docker run -v "${inputDir}/":/input/ -v "${outputDir}/":/output/ -t -i thomasweise/docker-bookbuilder book.md aitoa
  cd "${outputDir}"
  chown $USER *.*
