##
## Build with Travis.CI
##
sudo: required

language: generic

services:
  - docker

script:
- |
  baseDir="${pwd}"
  outputDir="${baseDir}/output"
  mkdir -p "${outputDir}"
  inputDir="${baseDir}/thomasWeise/atoia/book"
  docker run -v ${inputDir}:/input/ -v ${outputDir}:/output/ -t -i thomasweise/docker-bookbuilder book.md aitoa
  cd "${outputDir}"
  chown $USER *.*
